### ISSUE TITLE
Open URLS with login, and bypass cookies

### ISSUE THREAD

**Issue by BrutaleRalph** [foxxyz/multibrowse#10]
Hi,

Let me start off with what an amazing tool!

I see that the script should support Chromimum, where should I add --ignore-certificate-errors-spki-list
Could it also be possible to support login to a dashboard, with username & password.

**Comment by foxxyz** [comment]
Thanks @BrutaleRalph! 

To add Chromium flags, simply append them to the end of the command. For example:

```
multibrowse.exe example.com example2.com --ignore-certificate-errors-spki-list="yourfingerprints"
``` 

Basic Auth logins are supported by passing the credentials in the URL (see #6 for an example). If you have more info on the type of authentication used for your dashboard I could probably give you a more definitive answer.

**Comment by BrutaleRalph** [comment]
Great!, i'll try that tomorrow.
I simply updated my CA certificate instead -> Should have been done anyway I was just lazy.

Regarding the login, it's not basic auth but I might have found another solution with a different dashboard (Grafana).
Consider my question as closed.

**Comment by foxxyz** [comment]
Great stuff, thanks for using the library!

**Comment by BrutaleRalph** [comment]
Hi Foxxyz

I think I've found out which authentication is used on the site.
It runs on an internal IIS - and WWW-Authenticate with Windows Credentials.
But I cannot seem to get it working with https://username:password@somehost.com/admin

Any idea?

**Comment by foxxyz** [comment]
> It runs on an internal IIS - and WWW-Authenticate with Windows Credentials.

Do you mean NTLM? I have no experience with it, but I do know using `https://username:password@somehost.com` will only work for Basic authentication.

You may want to look into passing the [--auth-server-whitelist="*example.com,*foobar.com,*baz"](https://sites.google.com/a/chromium.org/dev/developers/design-documents/http-authentication) flag when invoking multibrowse.

**Comment by BrutaleRalph** [comment]
I meant NTLM yes, however, the suggestion doesn't work in my case.
