### ISSUE TITLE
Problem when execute from remote.

### ISSUE THREAD

**Issue by AlanCluet** [foxxyz/multibrowse#13]
Hi, in local machine everything works fine, but when i try to execute the program from a ssh connection i get this error.

Multibrowse v2.1.0
Can't open display
Traceback (most recent call last):
  File "/home/pi/Desktop/multibrowse/multibrowse.py", line 34, in <module>
    displays = sorted(sorted(platform.displays, key=itemgetter('x')), key=itemgetter('y'))
  File "/home/pi/Desktop/multibrowse/systems/linux.py", line 29, in displays
    for idx, line in enumerate(check_output(['xrandr']).decode('utf8').split('\n')):
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xrandr']' returned non-zero exit status 1.

There is any way to fix it?

Thanks and amazing program!

**Comment by foxxyz** [comment]
Hi Alan,

Thanks for the kind words!

Multibrowse uses xrandr under the hood, which won't find your display if
you're connected via SSH.

You may want to try explicitly telling it which display to use before
running it, using `export DISPLAY=:0` or `export DISPLAY=:1` depending on
which index your display is on.

Good luck!

**Comment by AlanCluet** [comment]
Many thanks i fixed all with ur advice.
