### ISSUE TITLE
displays sorted error

### ISSUE THREAD

**Issue by vadumont** [foxxyz/multibrowse#9]
Hello there,

When trying to use your multibrowse program on Ubuntu we get the traceback following : 

Multibrowse v2.0.0
Traceback (most recent call last):
  File "multibrowse.py", line 34, in <module>
    displays = sorted(sorted(platform.displays, key=itemgetter('x')), key=itemgetter('y'))
  File "systems/linux.py", line 32, in displays
    display = {k: int(v) for k, v in matches.groupdict().items()}
AttributeError: 'NoneType' object has no attribute 'groupdict'
[8330] Failed to execute script multibrowse

Do you have any idea ? 

Thank a lot

**Comment by foxxyz** [comment]
Sounds like `xrandr` might not be giving the expected output. Do you have it installed? Can you print the output of `xrandr`?

Please also provide distro version.

**Comment by vadumont** [comment]
Hello there,

Yes i have installed xrandr and that's the output :

Screen 0: minimum 320 x 200, current 11520 x 2160, maximum 16384 x 16384
DP-1 connected 3840x2160+7680+0 (normal left inverted right x axis y axis) 1210mm x 680mm
   3840x2160     29.98 +  30.00*   24.00    29.97    23.98
   1920x1080     60.00    50.00    59.94
   1920x1080i    60.00    50.00    59.94
   1680x1050     59.88
   1280x1024     60.02
   1440x900      59.90
   1280x720      60.00    50.00    59.94
   1024x768      60.00
   832x624       74.55
   800x600       60.32
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    60.00    59.94
   720x400       70.08
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2-1 connected primary 3840x2160+3840+0 (normal left inverted right x axis y axis) 1210mm x 680mm
   3840x2160     29.98 +  30.00*   24.00    29.97    23.98
   1920x1080     60.00    50.00    59.94
   1680x1050     59.88
   1280x1024     60.02
   1440x900      59.90
   1280x720      60.00    50.00    59.94
   1024x768      60.00
   832x624       74.55
   800x600       60.32
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    60.00    59.94
   720x400       70.08
DP-2-2 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 1210mm x 680mm
   3840x2160     29.98 +  30.00*   24.00    29.97    23.98
   1920x1080     60.00    50.00    59.94
   1680x1050     59.88
   1280x1024     60.02
   1440x900      59.90
   1280x720      60.00    50.00    59.94
   1024x768      60.00
   832x624       74.55
   800x600       60.32
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    60.00    59.94
   720x400       70.08



The distro is an ubunutu desktop 20.04.

Any idea ?

Thanks.

________________________________
De : foxxyz <notifications@github.com>
Envoyé : vendredi 21 août 2020 20:47
À : foxxyz/multibrowse <multibrowse@noreply.github.com>
Cc : vadumont <valentin.dumont03@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [foxxyz/multibrowse] displays sorted error (#9)


Sounds like xrandr might not be giving the expected output. Do you have it installed? Can you print the output of xrandr?

Please also provide distro version.

**Comment by foxxyz** [comment]
That looks like an expected format which should match the regex. I will test a build on an 20.04 instance and see if I can reproduce the problem.

If you find out any other information that would be helpful to reproduce, let me know.

**Comment by foxxyz** [comment]
Sorry, one more thing: which Python version are you running the script with?

**Comment by vadumont** [comment]
Hey,

I'm using python 3 !

Thank for your help

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by foxxyz** [comment]
I just tested it and did not encounter any issues. Perhaps you can help me debug the problem?

If you add a `print(line)` statement before the `matches = ...` line on [line 31 of `linux.py`](https://github.com/foxxyz/multibrowse/blob/master/systems/linux.py#L31) and run the script again, what does it print out?

**Comment by vadumont** [comment]
That's strange because it seems to find all the screens well :

Multibrowse v2.0.0
DP-1 connected 3840x2160+7680+0 (normal left inverted right x axis y axis) 1210mm x 680mm
DP-2-1 connected primary 3840x2160+3840+0 (normal left inverted right x axis y axis) 1210mm x 680mm
DP-2-2 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 1210mm x 680mm

We find the 3 differents screens here.
________________________________
De : foxxyz <notifications@github.com>
Envoyé : mardi 25 août 2020 00:29
À : foxxyz/multibrowse <multibrowse@noreply.github.com>
Cc : vadumont <valentin.dumont03@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [foxxyz/multibrowse] displays sorted error (#9)


I just tested it and did not encounter any issues. Perhaps you can help me debug the problem?

If you add a print(line) statement before the matches = ... line on line 31 of linux.py<https://github.com/foxxyz/multibrowse/blob/master/systems/linux.py#L31> and run the script again, what does it print out?

**Comment by vadumont** [comment]
Well now, he tells me that he opens the 3 URLS given on the 3 monitor but nothing appears :

Multibrowse v2.0.0

Opening https://www.microsoft.com on monitor 1
Opening https://www.microsoft.com on monitor 2
Opening https://www.microsoft.com on monitor 3


________________________________
De : foxxyz <notifications@github.com>
Envoyé : mardi 25 août 2020 00:29
À : foxxyz/multibrowse <multibrowse@noreply.github.com>
Cc : vadumont <valentin.dumont03@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [foxxyz/multibrowse] displays sorted error (#9)


I just tested it and did not encounter any issues. Perhaps you can help me debug the problem?

If you add a print(line) statement before the matches = ... line on line 31 of linux.py<https://github.com/foxxyz/multibrowse/blob/master/systems/linux.py#L31> and run the script again, what does it print out?

**Comment by foxxyz** [comment]
Do you have Chromium installed? What does `which chromium-browser` output?

Has the original issue been resolved?

**Comment by vadumont** [comment]
With chromium installed it works ! Thanks for your help !
________________________________
De : foxxyz <notifications@github.com>
Envoyé : mardi 25 août 2020 19:51
À : foxxyz/multibrowse <multibrowse@noreply.github.com>
Cc : vadumont <valentin.dumont03@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [foxxyz/multibrowse] displays sorted error (#9)


Do you have Chromium installed? What does which chromium-browser output?

Has the original issue been resolved?
